### ISSUE TITLE
What does the return value of IStateData::Update represent?

### ISSUE THREAD

**Issue by vctandrade** [ersh1/OpenAnimationReplacer#14]
I'm making a plugin that uses a state data component, but can't figure out what to return in this method.
Here is the [code line](https://github.com/ersh1/OpenAnimationReplacer/blob/main/src/API/OpenAnimationReplacer-ConditionTypes.h#L182) in question.

**Comment by ersh1** [comment]
That's a function you can implement if you want to run some code on every game update.
The return value is read [here](https://github.com/ersh1/OpenAnimationReplacer/blob/main/src/StateDataContainer.h#L35). Thus, returning true will ensure the state data doesn't get removed this frame.
I don't think I ended up using that in any condition.

**Comment by vctandrade** [comment]
Thank you for the quick response!
