### ISSUE TITLE
CTD on Kill Move

### ISSUE THREAD

**Issue by Shijikori** [ersh1/OpenAnimationReplacer#6]
I randomly get CTD, mostly on kill moves (or most repeatable with kill moves) with OAR loaded in.

I ran OAR version 2.0.2

OAR Dependencies : 
|Mod|Version|
|-|-|
|SKSE|2.2.3|
|Animation Queue Fix|1.0.1|
|Paired Animation Fix|1.0.1|
|Address Library for SKSE Plugins|8|

The animation set I was using was only [Sexy Idles](https://www.nexusmods.com/skyrimspecialedition/mods/76209) version 1.1

Installed OAR version and DAR version (for testing) of the animation set. Only one active at a time. Both versions would cause more frequent CTDs. Having the animation set disabled would only make the CTDs less frequent and harder to trigger.  The game could infinitely load when leaving to main menu while having OAR active with no animation sets.

None of those issues are present once OAR is disabled or using DAR version 1.1.3 instead of OAR.

I am running Skyrim SE on Linux under Proton 8.0.
I followed [this guide](https://www.nexusmods.com/skyrimspecialedition/mods/91500).

Let me know how I can further detail this report, a straight forward procedure would be appreciated.

**Comment by Shijikori** [comment]
This is one crash log example that I most often run into when encountering the issue.

[crash-2023-09-12-18-25-02.log](https://github.com/ersh1/OpenAnimationReplacer/files/12593530/crash-2023-09-12-18-25-02.log)

**Comment by mordquist** [comment]
I have similar problems with OAR crashing when running SSE with Proton. This happens for me both on my desktop (Fedora 38) and Steam Deck (SteamOS 3.5). When switching to DAR and leaving everything else the same, my crashes stop as well.

I'm gonna try and troubleshoot the issue some more and also produce a crash report. 

I have a different load order (>100 plugins) without Sexy Idles and my crashes are not limited to kill moves (even if that is the most common occurrence). Perhaps a better title for this issue would be "CTD when running on Linux (Proton)"?

**Comment by Shijikori** [comment]
I have reasons to believe this is not limited to Linux/Proton. Look at the bugs on the Nexus. There are random CTDs triggered by killmoves and animations from animals.

**Comment by BitterlyIronic** [comment]
I'm seeing this error too, seems to have a chance of happening on any paired animation. This is a crash log from the scene where Serana grabs Vyrthur in Dawnguard.

[crash-2023-12-03-17-21-30.log](https://github.com/ersh1/OpenAnimationReplacer/files/13539712/crash-2023-12-03-17-21-30.log)

**Comment by ersh1** [comment]
Should be fixed in 2.1.0
