### ISSUE TITLE
Unable to use MultiCondition in API

### ISSUE THREAD

**Issue by matiasmakipelto** [ersh1/OpenAnimationReplacer#8]
It is not possible to use the IMultiConditionComponent at the API as it is.

The IMultiConditionComponent exposes the function GetConditions() that returns a ConditionSet*.
However, ConditionSet is defined in BaseConditions.h which is not included in the API, so none of the functions of a ConditionSet may be called.

EvaluateAll() and EvaluateAny() functions should be exposed.

This would help me with my detection plugin to OAR.

**Comment by ersh1** [comment]
Fixed in 2.1.0
